#!/usr/bin/env python
import numpy as np
import os
import importlib
from commonmethods.filesys import *
from commonmethods.misc import *
from commonmethods.parse import *

def main(): 
    cwd = os.getcwd()
    parser = parseInput("dynpost.inp", cwd)
    parser.addInput("dynMethod", "Which dynamics method was used?")
    packageName = parser.dynMethod + "scripts."
    moduleName = packageName + parser.dynMethod + "post"
    mainName   = parser.dynMethod.upper() + "post" 
    inpName = packageName + parser.dynMethod + "inp"
    dynModule = importlib.import_module(moduleName)
    inpModule = importlib.import_module(inpName)
    parser = inpModule.initParser(parser) 
    mainMethod = getattr(dynModule,mainName) 
    postprocessing = mainMethod(parser, cwd) 
    postprocessing.performTasks()

if __name__ == "__main__":
    main()
